version: '3.8'
services:
  eureka-server:
    image: sandesh921/eureka-server:v1.0
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 5s
      retries: 5
      start_period: 10s

  service-one:
    image: sandesh921/service-one:v1.0
    container_name: service-one
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka

  service-two:
    image: sandesh921/service-two:v1.0
    container_name: service-two
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
